- name: variables
  hosts: localhost
  vars: #declare variables
    Course: "DEVOPSwithAWS"
    Trainer: "Sivakumar"
    started: "april"
  tasks
  - name: print information
    anisble.builtin.debug:
    msg: "Hi I am learning {{course}} from {{trainer}} in the month of {{started}}"


# - name: variables
#   hosts: localhost
#   vars: #variable declaration
#     Course: "Terraform"
#     Trainer: "Siva"
#     Duration: "15hrs"
#   tasks:
#   - name: print information
#     ansible.builtin.debug:
#       msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."